config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog

from idme.profiles.models import User, Admin, Enterprise
from idme.api.models import IDVerify
# from allauth.models import site
from allauth.mfa.models import Authenticator
from allauth.account.models import EmailAddress
from allauth.socialaccount.models import SocialAccount, SocialApp, SocialToken


from django_otp.admin import OTPAdminSite
from django_otp.plugins.otp_totp.models import TOTPDevice
from django_otp.plugins.otp_totp.admin import TOTPDeviceAdmin

from axes.models import AccessAttempt, AccessFailureLog, AccessLog


# from api.verify.views import FileUpdateView, DocumentScanView, PictureVerifyView, FileUpdatetestView, \
#     DocumentVerifiedView, HeadshotVerifiedView

from idme.profiles.views import ProfileView
# from rest_framework.routers import DefaultRouter
# from api.verify.views import FileUpdateView, DocumentScanView
# from api.chatbot.views import ChatGenerateView
#
# router = DefaultRouter()
#
# router.register(r"verify/", FileUpdateView, basename="verify")
# router.register(r"chat/", ChatGenerateView, basename="chat")

class OTPAdmin(OTPAdminSite):
   pass

admin_site = OTPAdmin(name='OTPAdmin')
# admin_site.register(User)
admin_site.register(TOTPDevice, TOTPDeviceAdmin)
model_objects = (
    User,
    Admin,
    IDVerify,
    # IDVerifyTmp,
    Enterprise,
    Authenticator,
    EmailAddress,
    SocialApp,
    SocialToken,
    SocialAccount,
    AccessAttempt,
    AccessLog,
    AccessFailureLog
    )

for m in model_objects:
    admin_site.register(m)
# admin_site.register(IDVerify)



urlpatterns = [
    # path(settings.ADMIN_URL_DEFENDER, include('defender.urls')), # defender admin
    path(settings.ADMIN_URL, admin_site.urls),
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path("", RedirectView.as_view(pattern_name="profiles:dispatch_login")),
    path("accounts/", include("allauth.urls")),
    path("accounts/profile/", ProfileView.as_view()),
    path("idme.apis/", include("idme.api.urls", namespace="idme-apis")),
    path("profiles/", include("idme.profiles.urls", namespace="profiles")),
    path("mobile/", include("idme.mobile.urls", namespace="mobile")),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("i18n/", include("django.conf.urls.i18n")),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

idme/api/urls.py
from django.urls import path, include, re_path

from . import views

app_name = "idmeapi"


urlpatterns = [
    re_path("idverify/", views.FileUpdateView.as_view(), name="idverify"),
    path("verify/", views.IDVerifyView.as_view(), name="verify"),
    path("sdashboard/", views.ConditionsView.as_view(), name="sdashboard"),

]

idme/mobile/urls.py
from django.urls import path, include, re_path
# from django.conf.urls import re_path
from django.views.generic import RedirectView
from django.views.decorators.cache import cache_page
from . import views

app_name = "mobile"

urlpatterns = [
    path("dash/", cache_page(60*15)(views.DashboardView.as_view()), name="dashboard"),
    ]

idme/profiles/urls.py
from django.urls import path, include, re_path
from . import views

app_name = "profiles"

enterprise_patterns = [
    path("create/", views.EnterpriseCreateView.as_view(), name="create"),
    path("edit/<int:pk>/", views.EnterpriseEditView.as_view(), name="edit"),
]


urlpatterns = [
    path('verify_mfa/', views.verify_mfa, name='verify_mfa'),
    path('profilemfa/', views.ProfilesMFAView.as_view(), name='profile_mfa'),
    path("logout",views.logout_page,name='logout'),
    path('disable-2fa/', views.disable_2fa, name='disable_2fa'),
    path("language/<int:pk>/", views.LanguageUpdateView.as_view(), name="language"),
    path("userinfo/<int:pk>/", views.ProfilesUpdateView.as_view(), name="userinfo"),
    path("activate/<int:pk>/", views.ProfileActivateView.as_view(), name="activate"),
    path("", views.ProfileDetailView.as_view(), name="profile"),
    path("edit/", views.ProfileView.as_view(), name="editprofile"),
    path("dispatch/", views.DispatchDeviceView.as_view(), name="dispatch"),
    path("mobilelogin/", views.MobileLoginView.as_view(), name="mobilelogin"),
    path("dispatch-login/", views.DispatchLoginView.as_view(), name="dispatch_login"),
    path("regular/", views.RegularUpdateView.as_view(), name="regular"),
    path("admin/", views.AdminUpdateView.as_view(), name="admin"),
    path("<int:pk>/add-review", views.ReviewCreateView.as_view(), name="review_create"),
    path("<int:pk>/contact-request/", views.ContactRequestView.as_view(), name="contact_request"),
    path("detail/<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("403/", views.ForbiddenView.as_view(), name="403"),
    path("conditions/", views.ConditionsView.as_view(), name="conditions"),
    path("privacy/", views.PrivacyView.as_view(), name="privacy"),
    # path("uploadusers/", views.user_upload, name="userupload"),
    # path("uploadposts/", views.posts_upload, name="uploadposts"),
    # path("createusers/", views.UsersCreate.as_view(), name="createusers"),
    # url('^createnewusers$', views.NewUserCreateView.as_view(), name="createnewusers"),
    path(
        "enterprise/",
        include((enterprise_patterns, "idme.profiles"), namespace="enterprise"),
    ),

]

idme/mobile/models.py
from django.db import models

# Create your models here.

idme/api/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.forms.models import inlineformset_factory
from . import models


class IDVerifyCreateForm(forms.ModelForm):
    class Meta:
        model = models.IDVerify
        fields = ["idcard_f"]

        labels = {
            "idcard": _("ID Card")
        }

idme/api/views.py
from django.views.generic import (
    UpdateView,
    RedirectView,
    CreateView,
    View,
    TemplateView,
    DetailView,
    ListView,
    DeleteView,
)
from django.http import JsonResponse
from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework.parsers import MultiPartParser, FormParser, FileUploadParser
from rest_framework.response import Response
from rest_framework import status

from django.urls import reverse_lazy
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _
from django.db import transaction
from guardian.shortcuts import assign_perm
from guardian.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt
from . import models, forms
from .mixins import JsonFormMixin
from idme.profiles.models import Admin
from .serializers import FileSerializer
from idme.profiles.models import Admin, User, Regular, Enterprise
from django.conf import settings
# Data analytics librairies
import json
import pandas as pd
import matplotlib.pyplot as plt
import datetime
import numpy as np
import seaborn as sns
from datetime import datetime as dt
from .id_recognize import idrecognize
from .tools import verifySignature, check_name, check_ip, check_address
from obfuskey import Obfuskey, alphabets
# Create your views here.

# Set the lenght of the hash key
obfuscator = Obfuskey(alphabets.BASE36, key_length=34)

class IDVerifyView(TemplateView):
    # model = models.IDVerify
    # form_class = forms.IDVerifyCreateForm
    template_name = "idmeapi/idverify.html"
    # success_url = reverse_lazy("coeanalytics:analytictypes:list")
    def get_context_data(self, **kwargs):
        postData = self.request.GET
        kwargs["userid"] = postData.get("user").upper()  #clfid: client for user id
        client_id = int(postData.get('client'))

        kwargs["fname"] = postData.get('fname')
        lname = postData.get('lname')
        kwargs["email"] = postData.get('email')
        kwargs["phone"] = postData.get('phone')
        kwargs["address"] = postData.get('cust_address')
        kwargs["lname"] = lname

        # convert last name to ASCII value and create a unique client/user ID
        # from the last name of the user, the client id and (minutes+seconds)
        lname_upper = lname.upper()
        nchars = len(lname_upper)
        # convert last name to ASCII representation
        num_val = sum(ord(lname_upper[byte]) << 8 * (nchars - byte - 1) for byte in range(nchars))
        # convert last name ASCII value to text
        # y = ''.join(chr((num_val >> 8 * (nchars - byte - 1)) & 0xFF) for byte in range(nchars))
        lname_left = str(num_val)[:20]
        int_lname_left = int(lname_left)
        user_id = "{:020d}".format(int_lname_left)
        clientid = "{:08d}".format(client_id)
        call_time = "{:04d}".format(dt.now().minute * 100 + dt.now().second)
        client_user_id = "{}X{}X{}".format(user_id, clientid, call_time)
        clientuser = obfuscator.get_value(client_user_id)


        # obj, created = models.IDVerify.objects.update_or_create(
        #     client_user=client_user_id, defaults={'temp_user_id': userid, 'temp_firstname': fname, 'temp_lastname': lname,
        #                                      'user_email': email, 'user_phone': phone, 'client_num': client})
        # clientid = "{:08d}".format(obj.client_num)
        # user_id = "{:020d}".format(num_val)
        # num_chars = "{:02d}".format(nchars)
        # clientid = "{:06d}".format(dt.now().hour*10000+dt.now().minute*100+dt.now().second)
        # call_time = "{:04d}".format(dt.now().minute*100+dt.now().second)
        # client_user_id = obfuscator.get_value("{}X{}X{}".format(user_id, clientid, num_chars))
        kwargs["clientid"] = clientuser
        return super(IDVerifyView, self).get_context_data(**kwargs)

class FileUpdateView(CreateView, JsonFormMixin):
  # parser_classes = (MultiPartParser, FormParser)
  # parser_classes = (FileUploadParser,)

  # @csrf_exempt
  def post(self, request, *args, **kwargs):
    # file_serializer = FileSerializer(data=request.data)

    # Get IP Address
    ip_address = check_ip(request)

    # get dat from template
    filename = request.FILES['file']
    side = int(request.POST.get("side"))
    client_user_id = request.POST.get("cid")
    temp_userid = request.POST.get("custid")
    temp_fname = request.POST.get("fname")
    temp_lname = request.POST.get("lname")
    temp_email = request.POST.get("custem")
    temp_phone = request.POST.get("custtel")
    temp_address = request.POST.get("custadd")

    clientuser = obfuscator.get_key(int(client_user_id))
    client_user = clientuser.split("X")
    customer = int(client_user[0])
    client_id = int(client_user[1])
    call_time = int(client_user[2])
    client = Admin.objects.get(pk=client_id)

    # clientuser_id = str(userid) + "@" + str(client)
    if side == 1:
        obj, created = models.IDVerify.objects.update_or_create(
            client_user=clientuser, defaults={'idcard_f': filename, 'ip_address': ip_address,
                                              'temp_address': temp_address, 'temp_user_id': temp_userid,
                                              'temp_firstname': temp_fname, 'temp_lastname': temp_lname,
                                              'user_email': temp_email, 'user_phone': temp_phone, 'client_num': client})
    elif side == 2:
        obj, created = models.IDVerify.objects.update_or_create(
            client_user=clientuser, defaults={'idcard_b': filename, 'ip_address': ip_address,
                                              'temp_address': temp_address, 'temp_user_id': temp_userid,
                                              'temp_firstname': temp_fname, 'temp_lastname': temp_lname,
                                              'user_email': temp_email, 'user_phone': temp_phone, 'client_num': client})

    lname_adjusted = obj.temp_lastname.strip().replace(" ", "_")
    result = idrecognize(str(client), lname_adjusted, side)

    if result:
        if side == 1:
            # temp_user_data = models.IDVerifyTmp.objects.filter(pk=customer).first()

            name_verified = False
            user_id_verified = False
            fname = ""
            lname = ""
            identification = result.get("Identity")
            if identification:
                identification.strip()
            else:
                identification = result.get("Driver's License Number")
            name = result.get("Name")
            city = result.get("City of Birth")
            dob = result.get("Date of Birth (DOB)").replace(".", "-")
            expiry_date = result.get("Expiration Date (EXP)").replace(".", "-")

            if check_name(name, temp_fname, temp_lname):
                name_verified = True
                fname = temp_fname
                lname = temp_lname

            if temp_userid and identification.lower() == temp_userid.lower():
                user_id_verified = True

            obj, created = models.IDVerify.objects.update_or_create(
                client_user=clientuser,
                defaults={'user_id': identification, 'lastname': lname, 'birth_city': city,
                          'dob': dob, 'expiry_date': expiry_date, 'firstname': fname, 'name': name,
                          'user_id_verified': user_id_verified, 'name_verified': name_verified}
            )
            result = {'id': identification, 'name': name, 'city': city, 'dob': dob, 'expire': expiry_date}
            # temp_user_data.delete()
        elif side == 2:
            address_verified = False
            # identification = result.get("Identity").strip()
            address = result.get("Address")
            gender = result.get("Gender")

            if check_address(address, temp_address):
                address_verified = True

            obj, created = models.IDVerify.objects.update_or_create(
                client_user=clientuser,
                defaults={'address': address, 'gender': gender, 'address_verified': address_verified}
            )
            result = {'address': address, 'gender': gender}
        # if expiry_date_text.find("-"):
        #     expiry_date_text = expiry_date_text.replace("-", "/")
        # print(expiry_date_text)
        # expiry_date = datetime.strptime(expiry_date_text, '%m/%d/%y').strftime('%m/%d/%Y')
        # print("expire:", expiry_date)
        # license_number = result.get("Driver's License Number")
        # print("user_id:", license_number)

    data = result

    return JsonResponse(data)
    # else:
    #     return Response(file_serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ConditionsView(LoginRequiredMixin, TemplateView):
    template_name = "../templates/conditions.html"

idme/mobile/views.py
from django.shortcuts import render
from django.views.generic import (
    CreateView,
    ListView,
    FormView,
    UpdateView,
    DetailView,
    DeleteView,
    TemplateView,
    View,
)
from guardian.mixins import LoginRequiredMixin
from idme.profiles.models import Admin, User
from idme.api import models
from idme.api.views import IDVerifyView, FileUpdateView
# Create your views here.


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "mobile/idverify.html"

idme/templates/profiles/activate_form.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% block css %}

    {{ block.super }}

{% endblock css %}



{% block page_title %}
    <h1 class="mb-0 pb-0 display-4" id="title">{% trans "Edit Profile" %}</h1>
    <nav class="breadcrumb-container d-inline-block" aria-label="breadcrumb">
        <ul class="breadcrumb pt-0">
            <li class="breadcrumb-item"><a href="{% url 'idmeapi:sdashboard' %}">{% trans "Home" %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'profiles:profile' %}">{% trans "Profile" %}</a></li>
            <li class="breadcrumb-item"><a href="">{% trans "Activate Form" %}</a></li>

        </ul>
    </nav>

{% endblock page_title %}

{% block main %}
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-12 col-md-5">
                <div class="card">
                    <div class="card-header border-0 pb-0">
                        <h3 style="display:inline;color:#333;font-size:1.4em;font-weight: bold;line-height: 25px;">{{ title }}</h3>

                        <hr/>
                    </div>
                    <div class="card-body">
                        <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
                            <span class="badge bg-danger text-uppercase">{% trans "Attention" %}</span>
                            <div class="alert alert-danger" role="alert">{% trans "Please Read Before you deactivate your account" %}</div>
                            <div class="alert alert-danger" role="alert">{% trans "Once you deactivate your account, you won't be able to access it!!" %}</div>
                            <div class="alert alert-danger" role="alert">{% trans "If you think you have deactivated your account by mistake, contact us to reactivate it for you" %}</div>
                            {{ form|crispy }}
                              <input type="submit" value='{% trans "Save" %}' class="btn btn-primary py-2 px-5">

                        </form>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

{% block create_button %}
    {{ block.super }}
{% endblock create_button %}

idme/templates/profiles/language_form.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_title %}

<title>{% trans "Languages" %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content={% trans "Streamline user onboarding and protect your business with our secure, AI-powered ID verification service, ensuring compliance and preventing fraud." %}>
<meta name="author" content="">
{% endblock head_title%}

{% block css %}

    {{ block.super }}

{% endblock css %}



{% block content_head %}
        <ul class="breadcrumb pt-0">
            <li class="breadcrumb-item"><a href="{% url 'idmeapi:sdashboard' %}">{% trans "Home" %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'profiles:profile' %}">{% trans "Profile" %}</a></li>
            <li class="breadcrumb-item"><a href="">{% trans "Language" %}</a></li>
        </ul>

{% endblock content_head %}

{% block content_body %}

        <div class="row gx-4">
            <div class="col-12 col-md-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">{{ title }}</h3>

                    </div>
                    <div class="card-body">
                        <form method='POST' action='' id="change-language-form" enctype='multipart/form-data'>{% csrf_token %}
                            {{ form|crispy }}
                            <input name="next" type="hidden" value="{{ redirect_to }}">
                            <input type="hidden" value="{{ langs.code }}" name="language" id="language"/>

                              <input type="button" value='{% trans "Save" %}' class="btn btn-success py-2 px-5 change-language" style="float: right;">

                        </form>
                        <br>
                    </div>
                    <div class="card-arrow">
                        <div class="card-arrow-top-left"></div>
                        <div class="card-arrow-top-right"></div>
                        <div class="card-arrow-bottom-left"></div>
                        <div class="card-arrow-bottom-right"></div>
                    </div>
                </div>
            </div>
        </div>
{% endblock content_body %}


{% block js %}
    {{ block.super }}
        <script>
    $(function () {


        $('.change-language').click(function (e) {
            $('#language').val($(this).attr('data-lang-code'));
            $('#change-language-form').submit();
        });
    });
</script>
{% endblock js %}

idme/templates/profiles/profile.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
    <meta charset="utf-8">
  <h1 class="mb-0 pb-0 display-4" id="title">{% trans "Profile Overview" %}</h1>
    <nav class="breadcrumb-container d-inline-block" aria-label="breadcrumb">
        <ul class="breadcrumb pt-0">
            <li class="breadcrumb-item"><a href="{% url 'idmeapi:sdashboard' %}">{% trans "Home" %}</a></li>
            <li class="breadcrumb-item"><a href="">{% trans "Profile" %}</a></li>

        </ul>
    </nav>

<link href={% static "assets/css/vendor.min.css" %} rel="stylesheet">
<link href={% static "assets/css/app.min.css" %} rel="stylesheet">

{% block content_head %}
<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">{% trans "Home" %}</a></li>
    <li class="breadcrumb-item active">{% trans "Profile" %}</li>
</ul>

<h1 class="page-header">
    {% trans "Profile Management" %}
</h1>
{% endblock content_head %}

{% block content_body %}

<div class="row gx-4">
    <div class="col-lg-6">
        <!-- Biography Start -->

        <div class="card mb-5">

            <div class="card-body">
                <div class="card">
                    <div class="card-body pt-4 pb-4 text-center">
                        {% if user.picture %}
                        <img class="img-fluid" src="{{ user.picture.url }}" style="border-radius: 50%; max-width: 200px; height: 200px" alt="">
                        {% else %}
                        <img class="img-fluid" style="border-radius: 50%; src={% static "pictures/user_placeholder.png" %} width="170" height="170" alt="">
                        {% endif %}
                    </div>
                    <div class="card-footer text-center">
                        <div class="h5 mb-0">{{ user.first_name }} {{ user.last_name }}</div>
                        <div class="text-muted">
                            <i data-cs-icon="pin" class="me-1"></i>
                            <span class="align-middle">{{ user.profile.city }}, {{ user.profile.country }}</span>
                        </div>
                    </div>
                    <div class="card-arrow">
                        <div class="card-arrow-top-left"></div>
                        <div class="card-arrow-top-right"></div>
                        <div class="card-arrow-bottom-left"></div>
                        <div class="card-arrow-bottom-right"></div>
                    </div>
                </div>




                <div class="card text-center">
                    <div class="card-body pt-4 pb-4">
                        <a class="nav-link active px-0 border-bottom border-separator-light"  href="{% url 'profiles:userinfo' user.pk %}" >
                            <i data-cs-icon="user" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "User Information" %}</span>
                        </a>
                        <a class="nav-link px-0 border-bottom border-separator-light"  href="{% url 'profiles:editprofile' %}" >
                            <i data-cs-icon="settings-1" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "Edit Profile" %}</span>
                        </a>
                        <a class="nav-link px-0 border-bottom border-separator-light"  href="{% url 'account_change_password' %}" >
                            <i data-cs-icon="lock-off" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "Manage Password"  %}</span>
                        </a>
                        <a class="nav-link px-0 border-bottom border-separator-light" href="{% url "account_email" %}" >
                        <i data-cs-icon="email" class="me-2" data-cs-size="17"></i>
                        <span class="align-middle">{% trans "Manage Emails" %}</span>
                        </a>
                        <a class="nav-link px-0 border-bottom border-separator-light" href="{% url 'profiles:language' user.pk %}" >
                            <i data-cs-icon="web" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "Prefered Language" %}</span>
                        </a>
                        <a class="nav-link px-0 border-bottom border-separator-light" href="{% url 'profiles:activate' user.pk %}" >
                            <i data-cs-icon="eye-off" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "Deactivate" %}</span>
                        </a>
                        <a class="nav-link active px-0 border-bottom border-separator-light"  href="{% url 'mfa_index' %}" >
                            <i data-cs-icon="user" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "Enable 2FA with Autheticator App" %}</span>
                        </a>
                        <a class="nav-link px-0 border-bottom border-separator-light" href="{% url 'profiles:logout' %}" >
                            <i data-cs-icon="logout" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "Logout" %}</span>
                        </a>


                    </div>
                    <div class="card-arrow">
                        <div class="card-arrow-top-left"></div>
                        <div class="card-arrow-top-right"></div>
                        <div class="card-arrow-bottom-left"></div>
                        <div class="card-arrow-bottom-right"></div>
                    </div>
                </div>
            </div>
            <div class="card-arrow">
                        <div class="card-arrow-top-left"></div>
                        <div class="card-arrow-top-right"></div>
                        <div class="card-arrow-bottom-left"></div>
                        <div class="card-arrow-bottom-right"></div>
                    </div>
        </div>
        <div class="card-arrow">
            <div class="card-arrow-top-left"></div>
            <div class="card-arrow-top-right"></div>
            <div class="card-arrow-bottom-left"></div>
            <div class="card-arrow-bottom-right"></div>
        </div>
    </div>
    <!-- Biography End -->
</div>




{% endblock content_body %}



{% block js %}
  {{ block.super }}

<script>
function goBack() {
  window.history.back();
}
</script>
{% endblock js %}

idme/templates/profiles/profile_form.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% block head_title %}

<title>{% trans "Personal Information" %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content={% trans "Streamline user onboarding and protect your business with our secure, AI-powered ID verification service, ensuring compliance and preventing fraud." %}>
<meta name="author" content="">
{% endblock head_title%}
{% block css %}

    {{ block.super }}

{% endblock css %}



{% block content_head %}
    <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'profiles:profile' %}">{% trans "Profile" %}</a></li>
        <li class="breadcrumb-item active">{% trans "Edit Your Profile" %}</li>
    </ul>

{% endblock content_head %}

{% block content_body %}

<div class="row gx-4">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">{{ title }}</h5>


            </div>
            <div class="card-body">
                <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}

                    {{ formset.management_form }}
                    {{ form|crispy }}
                    {% for profile_form in formset %}
                    {{ profile_form|crispy }}
                    {% endfor %}


                    <input type="submit" value='{% trans "Save" %}' class="btn btn-success py-2 px-5" style="float: right;">

                </form>
                <br>
            </div>
            <div class="card-arrow">
                <div class="card-arrow-top-left"></div>
                <div class="card-arrow-top-right"></div>
                <div class="card-arrow-bottom-left"></div>
                <div class="card-arrow-bottom-right"></div>
            </div>
        </div>
    </div>
</div>
{% endblock content_body %}

{% block js %}
  {{ block.super }}
<script>
function goBack() {
  window.history.back();
}
</script>


{% endblock js %}

idme/templates/profiles/user_form.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_title %}

<title>{% trans "ID Verify" %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content={% trans "Streamline user onboarding and protect your business with our secure, AI-powered ID verification service, ensuring compliance and preventing fraud." %}>
<meta name="author" content="">
{% endblock head_title%}

{% block css %}

    {{ block.super }}

{% endblock css %}



{% block content_head %}
<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'profiles:profile' %}">{% trans "Profile" %}</a></li>
    <li class="breadcrumb-item active">{% trans "ID Verify" %}</li>
</ul>

<h1 class="page-header">
    {% trans "Manage Your Info" %}
</h1>
{% endblock content_head %}



{% block content_body %}

        <div class="row justify-content-center">
            <div class="col-12 col-md-5">
                <div class="card">
                    <div class="card-header d-flex align-items-center bg-inverse bg-opacity-10 fw-400">
                        <h5 class="card-title">{{ title }}</h5>

                        <hr/>
                    </div>
                    <div class="card-body">
                        <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
                            {{ form|crispy }}
                              <input type="submit" value='{% trans "Save" %}' class="btn btn-success py-2 px-5" style="float: right;">

                        </form>
                        <br>
                    </div>
                    <div class="card-arrow">
                        <div class="card-arrow-top-left"></div>
                        <div class="card-arrow-top-right"></div>
                        <div class="card-arrow-bottom-left"></div>
                        <div class="card-arrow-bottom-right"></div>
                    </div>
                </div>
            </div>
        </div>
{% endblock content_body %}

{% block js %}
  {{ block.super }}

<script>
function goBack() {
  window.history.back();
}
</script>
{% endblock js %}